name: Export files

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianussimoddocker/freecad:1.1.0-py313-trixie

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run FreeCAD
        run: |
            mkdir /tmp/mirte-frame
            cp -r ./freecadFiles /tmp/mirte-frame
            cp -r ./fonts /tmp/mirte-frame
            cp -r ./scripts /tmp/mirte-frame
            cp ./bill_of_materials.md /tmp/mirte-frame
            cd /tmp/mirte-frame/scripts
            FreeCADCmd /tmp/mirte-frame/scripts/generate.py
      - name: Upload DXF
        uses: actions/upload-artifact@v7
        with:
          name: dxfs
          path: /tmp/mirte-frame/build/dxf/*
      - name: Upload STL
        uses: actions/upload-artifact@v7
        with:
          name: stls
          path: /tmp/mirte-frame/build/stl/*
      - name: Upload STEP
        uses: actions/upload-artifact@v7
        with:
          name: steps
          path: /tmp/mirte-frame/build/step/*
      - name: Zip artifacts
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          apt update
          apt install curl zip -y
          cd /tmp/mirte-frame/build
          zip -r /tmp/mirte-frame-stl.zip ./stl/*
          zip -r /tmp/mirte-frame-dxf.zip ./dxf/*
          zip -r /tmp/mirte-frame-step.zip ./step/*
      - name: Push to release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              /tmp/mirte-frame-dxf.zip
              /tmp/mirte-frame-stl.zip
              /tmp/mirte-frame-step.zip
              /tmp/mirte-frame/bill_of_materials.md
